config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
      resources :oxxos, :path => 'oxxo'
  end
end

app/models/spree/admin.rb
module Spree::Admin
  def self.table_name_prefix
    'spree_admin_'
  end
end

app/models/spree/oxxo.rb
module Spree
  class ImportError < StandardError; end;

  class Oxxo < ActiveRecord::Base
    attr_accessible :oxxo_file
    has_attached_file :oxxo_file, 
			:path => ':rails_root/public/spree/order_data/data-files/:basename.:extension',
			:url => '/spree/order_data/data-files/:basename.:extension'

    validates_attachment_presence :oxxo_file
    serialize :order_ids, Array

    cattr_accessor :settings

    def orders
      Spree::Order.where :id => order_ids
    end
    
    include Spree::Core::S3Support
    supports_s3 :oxxo_file

    require 'csv'
    require 'pp'
    require 'open-uri'
    require 'tempfile'

    state_machine :initial => :created do

      event :start do
        transition :to => :started, :from => :created
      end
      event :complete do
        transition :to => :completed, :from => :started
      end
      event :failure do
        transition :to => :failed, :from => :started
      end

      before_transition :to => [:failed] do |import|
        import.order_ids = []
        import.failed_at = Time.now
        import.completed_at = nil
      end

      before_transition :to => [:completed] do |import|
        import.failed_at = nil
        import.completed_at = Time.now
      end
    end

    def state_datetime
      if failed?
        failed_at
      elsif completed?
        completed_at
      else
        Time.now
      end
    end
      
    def import_data!(_transaction=true)
      start
      if _transaction
        transaction do
          _import_data
        end
      else
        _import_data
      end
    rescue Exception => exp
      log("An error occurred during import, please check file and try again. (#{exp.message})\n#{exp.backtrace.join('\n')}", :error)
      failure
      raise ImportError, exp.message
    end

    def _import_data
      unless Spree::Oxxo.settings[:aws]
        rows = CSV.read(self.oxxo_file.path)
      else
        _tempfile 'import', 'csv', open(self.oxxo_file.url).read
        csv_file = "#{Rails.root}/tmp/import_oxxo_csv_#{Process.pid}"
        rows = CSV.read(csv_file)
      end
      
      headers= Spree::Oxxo.settings[:column_mappings]

      log("Importing orders for #{self.oxxo_file_file_name} began at #{Time.now}")
      rows[Spree::Oxxo.settings[:rows_to_skip]..-1].each do |row|
        order_information = {}
        
        headers.each do |k, v|
          order_information[k] = row[v]
        end

        check_order_paid(order_information)
      end

      complete
      return [:notice, "Product data was successfully imported."]
    end
    
    private
    def check_order_paid(order)
      log "\n Order to pay \n"
      log "\n #{pp order} \n\n"
      code = _barcode(order)
      payment = Spree::Payment.find_by_barcode(code)
      begin
        unless payment.state == "completed"
          payment.complete!
          Spree::OrderUpdater.new(payment.order).update_payment_state
        end
        order_ids << payment.order.id
      rescue
        log "Not exists #{code} order"
      end
    end

    def _barcode order
      if order[:rpu2].to_i > 1
        code = (order[:rpu1] + order[:rpu2]).gsub(' ', '')
        last_position = code.index('0000000000')
        code[0..last_position - 1]
      else
        order[:rpu1]
      end
    end

		def _tempfile name, extension, data
			file = Tempfile.open([name, ".#{extension}"],"#{Rails.root}/tmp/")
			begin
				file.binmode
				file.write(data)
			ensure
				file.close
			end
			
			if extension == 'csv'
				File.rename(file.path, "#{Rails.root}/tmp/#{name}_oxxo_csv_#{Process.pid}")
			else
				File.rename(file.path, "#{Rails.root}/tmp/#{name}.#{extension}")
			end
			file.unlink
		end

    ### MISC HELPERS ####

    #Log a message to a file - logs in standard Rails format to logfile set up in the import_products initializer
    #and console.
    #Message is string, severity symbol - either :info, :warn or :error

    def log(message, severity = :info)
      @rake_log ||= ActiveSupport::BufferedLogger.new(Spree::Oxxo.settings[:log_to])
      message = "[#{Time.now.to_s(:db)}] [#{severity.to_s.capitalize}] #{message}\n"
      @rake_log.send severity, message
      puts message
    end

  end
end

app/controllers/spree/admin/oxxos_controller.rb
module Spree
  module Admin
    class OxxosController < BaseController

      def index
        @oxxo = Spree::Oxxo.new
      end

      def create
        @order_import = Spree::Oxxo.create(params[:oxxo])
        Delayed::Job.enqueue SpreeOxxo::ImportJob.new(@order_import, current_user)
        flash[:notice] = t('oxxo.order_processing')
        redirect_to admin_oxxos_path
      end

      def show
        @oxxo = Spree::Oxxo.find(params[:id])
        @orders = @oxxo.orders
      end

      def destroy
        @oxxo = Spree::Oxxo.find(params[:id])
        if @oxxo.destroy
          flash[:notice] = t('oxxo.delete_order_successful')
        end
        redirect_to admin_oxxos_path
      end

    end
  end
end

app/helpers/spree/admin/oxxos_helper.rb
module Spree::Admin::OxxosHelper
end

app/views/spree/admin/oxxos/index.html.erb
<% content_for :page_title do %>
  <%= t('oxxo.import_orders') %>
<% end %>

<%= render :partial => 'spree/admin/shared/order_sub_menu' %>
<%= render "spree/shared/error_messages", :target => @oxxo %>

<%= form_for([:admin, @oxxo], :method => :post, :html => { :multipart => true }) do |f| %>
  <fieldset>
    <%= f.field_container :oxxo_file do%>
      <%= f.label :oxxo_file, t('oxxo.form.import.new.file') %>
      <%= f.file_field :oxxo_file %>
      <%= f.error_message_on :oxxo_file %>
    <% end %>
  </fieldset>
  <p class='form-buttons'>
    <%= button t('actions.create') %>
  </p>
<% end %>

<table>
  <tr>
    <th><%= t('oxxo.table.oxxo_files.title.date_creation')%></th>
    <th><%= t('oxxo.table.oxxo_files.title.csv_name')%></th>
    <th><%= t('oxxo.table.oxxo_files.title.status')%></th>
    <th><%= t('oxxo.table.oxxo_files.title.date_status')%></th>
    <th><%= t('oxxo.table.oxxo_files.title.orders_imported')%></th>
    <th><%= t('oxxo.table.oxxo_files.title.actions')%></th>
  </tr>
  <% Spree::Oxxo.order('created_at DESC').all.each do |order_imported| %>
    <tr>
      <td><%= time_ago_in_words order_imported.created_at, true %> ago</td>
      <td><%= order_imported.oxxo_file_file_name %></td>
      <td><%= t(order_imported.state, :scope => "oxxo.state") -%></td>
      <td><%= time_ago_in_words order_imported.state_datetime -%> ago</td>
      <td><%= order_imported.order_ids.size -%></td>
      <td>
        <%= link_to 'Show', admin_oxxo_path(order_imported) -%>
      </td>
    </tr>
  <% end %>
</table>
<script>
  $(".tab-with-icon:eq(1)").addClass("selected");
</script>

app/views/spree/admin/oxxos/show.html.erb
<% content_for :page_title do %>
  <%= t('oxxo.show_order') %>
<% end %>


<%= render :partial => 'spree/admin/shared/order_sub_menu' %>

<table class="index" id="listing_orders">
  <tr data-hook="admin_orders_index_headers">
    <th><%= t('oxxo.place') %></th>
    <th><%= t('oxxo.store') %></th>
    <th><%= t('oxxo.date') %></th>
    <th><%= t('oxxo.time') %></th>
    <th><%= t('oxxo.number') %></th>
    <th><%= t('oxxo.barcode') %></th>
    <th><%= t('oxxo.amount') %></th>
    <th data-hook="admin_orders_index_header_actions"></th>
  </tr>
  <% @orders.each do |order| %>
    <tr <%= "style='color: red;'" %> id="<%= dom_id order %>" data-hook="admin_orders_index_rows">
      <td></td>
      <td></td>
      <td></td>
      <td></td>
      <td><%= order.number rescue '' %></td>
      <td><%= order.payment.barcode rescue '' %></td>
      <td><%= order.display_total rescue '' %></td>
      <td class="actions" data-hook="admin_orders_index_row_actions">
        <%= link_to "Edit", edit_admin_order_path(order), :class => 'edit' %>
      </td>
  </tr>
<% end %>
</table>
<script>
	$(".tab-with-icon:eq(2)").addClass("selected");
</script>

app/views/spree/admin/shared/_order_sub_menu.html.erb
<% content_for :sub_menu do %>
  <ul id="sub_nav" data-hook="admin_order_sub_tabs" class="inline-menu">
  </ul>
<% end %>